/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conexion.AdminConexion;
import events.Exporter;
import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 30047818
 */
public class KforceQueryTermUser extends javax.swing.JFrame {
      JTable table;
      ResultSet rs;
    /**
     * Creates new form KforceQueryTermUser
     */
    public KforceQueryTermUser() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        allUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void allUsers() throws SQLException
    {
        
        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report");
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
            Jlabel_ttuser();
    }
    
    public void Jlabel_ttuser()
    {
        int tt_users = this.jt_terminated.getRowCount();
        this.jl_tt_user.setText("Total Users: "+tt_users);
    }
    
    public void TermUserW() throws SQLException
    {
        String var_winid = jtext_winid.getText();
        
        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where UserName='"+var_winid+"'");
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    
    public void TermUserF() throws SQLException
    {
        
        String var_first = jtext_firstname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where FirstName like '"+var_first+"'");
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
       
    public void TermUserL() throws SQLException
    {
        
        String var_Last = jtext_lastname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where FirstName like '"+var_Last+"'");
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    public void TermUserWF() throws SQLException
    {
        String var_winid = jtext_winid.getText();
        String var_first = jtext_firstname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where UserName ='"+var_winid+"' and FirstName='"+var_first+"'" );
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    
    public void TermUserWL() throws SQLException
    {
        String var_winid = jtext_winid.getText();
        String var_Last = jtext_lastname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where UserName ='"+var_winid+"' and LastName='"+var_Last+"'" );
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    
    
    public void TermUserWFL() throws SQLException
    {
        String var_winid = jtext_winid.getText();
        String var_first = jtext_firstname.getText();
        String var_Last = jtext_lastname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where UserName ='"+var_winid+"' and FirstName='"+var_first+"' and LastName='"+var_Last+"'" );
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    
    public void TermUserFL() throws SQLException
    {
        String var_first = jtext_firstname.getText();
        String var_Last = jtext_lastname.getText();

        rs = AdminConexion.Consult("Select * from knova.RPT_Kforce_TermRevokeDeleted_Users_Report where FirstName='"+var_first+"' and LastName='"+var_Last+"'" );
        ResultSetMetaData rsmt =rs.getMetaData();
        int numCol = rsmt.getColumnCount();
        
        //crear un objeto de la tabla modelo
            DefaultTableModel modelo = new DefaultTableModel();
            this.jt_terminated.setModel(modelo);
            
            //add the column names
            for(int x=1; x<=numCol; x++){
                modelo.addColumn(rsmt.getColumnLabel(x));
            }
            
            //add records
            while(rs.next())
            {
                Object [] fila = new Object[numCol];
                        
                 for(int y=0; y<numCol; y++)
                 {
                    fila [y]=rs.getObject(y+1);
                 }
            
                 modelo.addRow(fila);
            }
            rs.close();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jl_winid = new javax.swing.JLabel();
        jl_name = new javax.swing.JLabel();
        jl_lastname = new javax.swing.JLabel();
        jtext_winid = new javax.swing.JTextField();
        jtext_firstname = new javax.swing.JTextField();
        jtext_lastname = new javax.swing.JTextField();
        btnConsult = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_terminated = new javax.swing.JTable();
        jl_tt_user = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kforce Search Terminated Users");

        jl_winid.setText("Enter User WINID:");

        jl_name.setText("Enter User First Name:");

        jl_lastname.setText("Enter User Last Name:");

        btnConsult.setText("Search");
        btnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultActionPerformed(evt);
            }
        });

        btnExport.setText("Export Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jt_terminated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_terminated);

        jl_tt_user.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_tt_user.setText("jl_tt_user");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_name)
                                    .addComponent(jl_winid)
                                    .addComponent(jl_lastname))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtext_winid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtext_firstname)
                                    .addComponent(jtext_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnExport)
                                .addGap(33, 33, 33)
                                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jl_tt_user))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(185, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_winid)
                    .addComponent(jtext_winid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_name)
                    .addComponent(jtext_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_lastname)
                    .addComponent(jtext_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_tt_user))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsult)
                    .addComponent(btnExport)
                    .addComponent(btnMainMenu)
                    .addComponent(btnExit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Return to Main Menu");
        dispose();
        new PrincipalMenu().setVisible(true);
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultActionPerformed
        // TODO add your handling code here:
        if(jtext_winid.getText().isEmpty() && jtext_firstname.getText().isEmpty() && jtext_lastname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter WINID or FirstName or LastName", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtext_winid.getText().length() > 0 && jtext_firstname.getText().isEmpty() && jtext_lastname.getText().isEmpty())
        {
            try {
                //JOptionPane.showMessageDialog(null, "prueba");
                TermUserW();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserW();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().isEmpty() && jtext_firstname.getText().length() > 0 && jtext_lastname.getText().isEmpty())
        {
            try {
                TermUserF();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserF();
                    Jlabel_ttuser();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().isEmpty() && jtext_firstname.getText().isEmpty() && jtext_lastname.getText().length() > 0)
        {
            try {
                TermUserL();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserL();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().length() > 0 && jtext_firstname.getText().length() > 0 && jtext_lastname.getText().length() > 0)
        {
            try {
                TermUserWFL();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserWFL();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().length() > 0 && jtext_firstname.getText().length() > 0 && jtext_lastname.getText().isEmpty())
        {
            try {
                TermUserWF();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserWF();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().length() > 0 && jtext_firstname.getText().isEmpty() && jtext_lastname.getText().length()> 0)
        {
            try {
                TermUserWL();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserWL();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jtext_winid.getText().isEmpty() && jtext_firstname.getText().length()> 0 && jtext_lastname.getText().length()> 0)
        {
            try {
                TermUserFL();
                int tt_user=this.jt_terminated.getRowCount();
                Jlabel_ttuser();
                if(tt_user == 0)
                {
                    JOptionPane.showMessageDialog(null, "No user found");
                }
                else{
                    TermUserFL();
                    Jlabel_ttuser();
                }
            } catch (SQLException ex) {
                Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConsultActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
               if(this.jt_terminated.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(null, "No Users to Export", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //this is a JFilter to choose where stored the file
        int totalR= jt_terminated.getRowCount();
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", ".xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Saved File");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION)
        {
            List<JTable> tb = new ArrayList<>();
            List<String>nom = new ArrayList<>();
            tb.add(jt_terminated);
            nom.add("Term Users Report Kforce");
            String file = chooser.getSelectedFile().toString().concat(".xls");
            //here is executed the method
            try
            {
                Exporter e = new Exporter(new File(file),tb,nom);
                if(e.export())
                {
                    JOptionPane.showMessageDialog(null, "Total Records exported to Excel: " +totalR, "Term User Report", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"There was an error" + e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KforceQueryTermUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KforceQueryTermUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KforceQueryTermUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KforceQueryTermUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KforceQueryTermUser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KforceQueryTermUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jl_lastname;
    private javax.swing.JLabel jl_name;
    private javax.swing.JLabel jl_tt_user;
    private javax.swing.JLabel jl_winid;
    private javax.swing.JTable jt_terminated;
    private javax.swing.JTextField jtext_firstname;
    private javax.swing.JTextField jtext_lastname;
    private javax.swing.JTextField jtext_winid;
    // End of variables declaration//GEN-END:variables
}
